services:
  configsvr:
    container_name: configsvr
    image: mongo:latest
    restart: always
    command: mongod --configsvr --replSet config_server --bind_ip_all --port 27017
    networks:
      app-network:
        ipv4_address: 173.17.0.2
    ports:
      - '27017:27017'
    volumes:
      - ./data/configsvr:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      start_period: 10s

  shard1:
    container_name: shard1
    image: mongo:latest
    restart: always
    command: ['mongod', '--shardsvr', '--replSet', 'shard1', '--bind_ip_all', '--port', '27018']
    networks:
      app-network:
        ipv4_address: 173.17.0.3
    ports:
      - '27018:27018'
    volumes:
      - ./data/shard1:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27018/test --quiet
      interval: 5s
      start_period: 15s

  shard2:
    container_name: shard2
    image: mongo:latest
    command: ['mongod', '--shardsvr', '--replSet', 'shard2', '--bind_ip_all', '--port', '27019']
    networks:
      app-network:
        ipv4_address: 173.17.0.4
    ports:
      - '27019:27019'
    volumes:
      - ./data/shard2:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27019/test --quiet
      interval: 5s
      start_period: 15s

  mongos_router:
    container_name: mongos_router
    image: mongo:latest
    depends_on:
      - configsvr
      - shard1
      - shard2
    restart: always
    ports:
      - '27020:27020'
    command: ['mongos', '--configdb', 'config_server/configsvr:27017', '--bind_ip_all', '--port', '27020']
    networks:
      app-network:
        ipv4_address: 173.17.0.5
    healthcheck:
      test: echo 'db.adminCommand("ping").ok' | mongosh mongos_router:27020/admin --quiet
      interval: 5s
      start_period: 10s

  mongo_setup:
    container_name: mongo_setup
    image: mongo:latest
    depends_on:
      - mongos_router
    volumes:
      - ./scripts:/scripts
    command: ['bash', '/scripts/mongo-init.sh']
    networks:
      app-network:
        ipv4_address: 173.17.0.6

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongo_setup
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis_1:6379"
    networks:
      app-network:
        ipv4_address: 173.17.0.10

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16